services:
  milvus:
    image: milvusdb/milvus:v2.4.4
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_USE_EMBED: "true"
      ETCD_DATA_DIR: /var/lib/milvus/etcd
      ETCD_CONFIG_PATH: /milvus/configs/embedEtcd.yaml
      COMMON_STORAGETYPE: local
      DEPLOY_MODE: STANDALONE
    volumes:
      - ./volumes/milvus:/var/lib/milvus
      - ./embedEtcd.yaml:/milvus/configs/embedEtcd.yaml:ro
      - ./user.yaml:/milvus/configs/user.yaml:ro
    ports:
      - "19530:19530"  
      - "9091:9091"     
      - "2379:2379"     
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9091/healthz || wget -qO- http://localhost:9091/healthz || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
    restart: unless-stopped

  api:
    image: ersiliaos/nns
    container_name: nns-api
    depends_on:
      milvus:
        condition: service_healthy
    environment:
      - MILVUS_ADDR=milvus:19530
    ports:
      - "8080:8080"
    restart: unless-stopped
